const mongoose = require('mongoose');

/*
  A "session" is created when a user selects a mode on the frontend
  (Exam Stress, Sleep Anxiety, Panic Mode, or Focus Mode).
  It stores the selected mode, the backend-generated recommendation,
  optional stress check-in answers (for future survey sections),
  and a reference to a logged-in user (null until auth is added).
*/

const sessionSchema = new mongoose.Schema({

  // Which mode the user selected on the hero screen
  mode: {
    type: String,
    enum: ['exam', 'sleep', 'panic', 'focus'],
    required: true
  },

  // Optional: stress check-in answers (for future Light/Sound/Breathing forms)
  checkIn: {
    stressLevel:      { type: Number, min: 1, max: 10 }, // How stressed? 1-10
    energyLevel:      { type: Number, min: 1, max: 10 }, // Energy level 1-10
    sleepLastNight:   { type: Number },                  // Hours slept
    notes:            { type: String, maxlength: 500 }   // Free text
  },

  // Recommendation generated by the backend based on mode + check-in
  recommendation: {
    title:       { type: String },
    message:     { type: String },
    techniques:  [{ type: String }],  // Array of suggested techniques
    duration:    { type: String }     // e.g. "5–10 minutes"
  },

  // Linked user (null = anonymous; populated once login is added)
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },

  // When this session was started
  createdAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('Session', sessionSchema);
